fitb_data_param:
  phase: "test"
  num_cand: 4
  data_root: data/polyvore # data root
  image_root: data/polyvore # data root
  data_set: tuples_53 # data set
  num_workers: 6 # number of workers
  use_lmdb: true # use lmbd data
  use_semantic: true # use sentance data
  use_visual: true # use visual data

net_param:
  name: ColdStart
  num_users: 53 # number of users
  dim: 128 # dimension of binary codes
  backbone: alexnet # backbone for feature extractor
  hash_types: 3 # type of hash codes
  scale_tanh: true # use scale tahn
  use_semantic: true # use semantic features
  use_visual: true # user visdual features

  big_data_param:
    phase: test
    batch_size: 64
    data_root: data/polyvore # data root
    data_set: tuples_630 # data set
    data_mode: TuplePair
    shuffle: False
    num_workers: 6 # number of workers
    use_lmdb: true # use lmbd data
    use_semantic: true # use sentance data
    use_visual: true # use visual data
  small_data_param:
    phase: train
    batch_size: 64
    data_root: data/polyvore # data root
    data_set: tuples_53_5 # data set
    data_mode: TuplePair
    shuffle: False
    num_workers: 6 # number of workers
    use_lmdb: true # use lmbd data
    use_semantic: true # use sentance data
    use_visual: true # use visual data
  data_file: results/CS.npz
  gpus: [0]

gpus: [0]
load_trained: models/fashion_hash_net_vse_t3_u630_53_best.net
result_file: results/fashion_hash_net_vse_t3_u630_53.npz
log_level: INFO